### ISSUE TITLE
读帖返回时意外回到桌面

### ISSUE THREAD

**Issue by zhengnairen** [ihainan/BITUnion-for-Android#3]
读帖时，如果单击左上角左箭头，会正常回到帖子列表。

但是，如果读帖时，切换到其它应用，然后再切换回BU，然后再按左左上角左箭头，会直接闪回到手机桌面。此时切换后台应用回到BU，会发现仍在读帖界面，未回到帖子列表。

使用安卓虚拟按键的返回键有同样效果。

**Comment by ihainan** [comment]
这个问题我也发现了，的确是一个 Bug，适配 Android N 的多窗口特性时候，设置了一个不恰当的 flag，会在下一版本修复的，多谢！
